// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOU_c_nhtsFKjzO_BmpqKPTX_O6cvFV2k',
    appId: '1:733722559391:web:40a6614071577257bfb3aa',
    messagingSenderId: '733722559391',
    projectId: 'barakahhub-ef014',
    authDomain: 'barakahhub-ef014.firebaseapp.com',
    storageBucket: 'barakahhub-ef014.firebasestorage.app',
    measurementId: 'G-CBKGQQZ9FL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKYLsX6PUUFjf_rKroJttC_Y0SEvGe4g',
    appId: '1:364681850525:android:3f99a42e7b3ddf517c6e74',
    messagingSenderId: '364681850525',
    projectId: 'barakahhub-d803b',
    storageBucket: 'barakahhub-d803b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCI0TWebBObe1MiS20g8HhdJs5mjSpZU',
    appId: '1:364681850525:ios:75dd5e18c026db0f7c6e74',
    messagingSenderId: '364681850525',
    projectId: 'barakahhub-d803b',
    storageBucket: 'barakahhub-d803b.firebasestorage.app',
    iosBundleId: 'com.example.barakahHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCI0TWebBObe1MiS20g8HhdJs5mjSpZU',
    appId: '1:364681850525:ios:75dd5e18c026db0f7c6e74',
    messagingSenderId: '364681850525',
    projectId: 'barakahhub-d803b',
    storageBucket: 'barakahhub-d803b.firebasestorage.app',
    iosBundleId: 'com.example.barakahHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAetHbBax5aYWk8blgeYSf15mATcHDkgHE',
    appId: '1:364681850525:web:0af2d520c450ac677c6e74',
    messagingSenderId: '364681850525',
    projectId: 'barakahhub-d803b',
    authDomain: 'barakahhub-d803b.firebaseapp.com',
    storageBucket: 'barakahhub-d803b.firebasestorage.app',
    measurementId: 'G-LQXPJDKFYZ',
  );
}
